
package org.occ.p3.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "reservationWs", targetNamespace = "http://webservices.p3.occ.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationWs {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://webservices.p3.occ.org/", className = "org.occ.p3.webservices.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://webservices.p3.occ.org/", className = "org.occ.p3.webservices.InitResponse")
    @Action(input = "http://webservices.p3.occ.org/reservationWs/initRequest", output = "http://webservices.p3.occ.org/reservationWs/initResponse")
    public void init();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelReservation", targetNamespace = "http://webservices.p3.occ.org/", className = "org.occ.p3.webservices.CancelReservation")
    @ResponseWrapper(localName = "cancelReservationResponse", targetNamespace = "http://webservices.p3.occ.org/", className = "org.occ.p3.webservices.CancelReservationResponse")
    @Action(input = "http://webservices.p3.occ.org/reservationWs/cancelReservationRequest", output = "http://webservices.p3.occ.org/reservationWs/cancelReservationResponse")
    public Boolean cancelReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveWork", targetNamespace = "http://webservices.p3.occ.org/", className = "org.occ.p3.webservices.ReserveWork")
    @ResponseWrapper(localName = "reserveWorkResponse", targetNamespace = "http://webservices.p3.occ.org/", className = "org.occ.p3.webservices.ReserveWorkResponse")
    @Action(input = "http://webservices.p3.occ.org/reservationWs/reserveWorkRequest", output = "http://webservices.p3.occ.org/reservationWs/reserveWorkResponse")
    public Boolean reserveWork(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

}
